/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface BatchAcknowledgeAlarm {
  readonly acknowledgeActionRequests: [];
}

export interface BatchDisableAlarm {
  readonly disableActionRequests: [];
}

export interface BatchEnableAlarm {
  readonly enableActionRequests: [];
}

export interface BatchPutMessage {
  readonly messages: [];
}

export interface BatchResetAlarm {
  readonly resetActionRequests: [];
}

export interface BatchSnoozeAlarm {
  readonly snoozeActionRequests: [];
}

export interface BatchUpdateDetector {
  readonly detectors: [];
}

export interface DescribeAlarm {
  readonly alarmModelName: string;
  readonly keyValue?: string;
}

export interface DescribeDetector {
  readonly detectorModelName: string;
  readonly keyValue?: string;
}

export interface ListAlarms {
  readonly alarmModelName: string;
  readonly nextToken?: string;
  readonly maxResults?: number;
}

export interface ListDetectors {
  readonly detectorModelName: string;
  readonly stateName?: string;
  readonly nextToken?: string;
  readonly maxResults?: number;
}

export interface AcknowledgeActionConfiguration {
  readonly note?: string;
}

export interface AcknowledgeAlarmActionRequest {
  readonly requestId: string;
  readonly alarmModelName: string;
  readonly keyValue?: string;
  readonly note?: string;
}

export interface Alarm {
  readonly alarmModelName?: string;
  readonly alarmModelVersion?: string;
  readonly keyValue?: string;
  readonly alarmState?: AlarmState;
  readonly severity?: number;
  readonly creationTime?: Date;
  readonly lastUpdateTime?: Date;
}

export interface AlarmState {
  readonly stateName?: string;
  readonly ruleEvaluation?: RuleEvaluation;
  readonly customerAction?: CustomerAction;
  readonly systemEvent?: SystemEvent;
}

export interface AlarmSummary {
  readonly alarmModelName?: string;
  readonly alarmModelVersion?: string;
  readonly keyValue?: string;
  readonly stateName?: string;
  readonly creationTime?: Date;
  readonly lastUpdateTime?: Date;
}

export interface BatchAcknowledgeAlarmRequest {
  readonly acknowledgeActionRequests: [];
}

export interface BatchAcknowledgeAlarmResponse {
  readonly errorEntries?: [];
}

export interface BatchAlarmActionErrorEntry {
  readonly requestId?: string;
  readonly errorCode?: string;
  readonly errorMessage?: string;
}

export interface BatchDisableAlarmRequest {
  readonly disableActionRequests: [];
}

export interface BatchDisableAlarmResponse {
  readonly errorEntries?: [];
}

export interface BatchEnableAlarmRequest {
  readonly enableActionRequests: [];
}

export interface BatchEnableAlarmResponse {
  readonly errorEntries?: [];
}

export interface BatchPutMessageErrorEntry {
  readonly messageId?: string;
  readonly errorCode?: string;
  readonly errorMessage?: string;
}

export interface BatchPutMessageRequest {
  readonly messages: [];
}

export interface BatchPutMessageResponse {
  readonly BatchPutMessageErrorEntries?: [];
}

export interface BatchResetAlarmRequest {
  readonly resetActionRequests: [];
}

export interface BatchResetAlarmResponse {
  readonly errorEntries?: [];
}

export interface BatchSnoozeAlarmRequest {
  readonly snoozeActionRequests: [];
}

export interface BatchSnoozeAlarmResponse {
  readonly errorEntries?: [];
}

export interface BatchUpdateDetectorErrorEntry {
  readonly messageId?: string;
  readonly errorCode?: string;
  readonly errorMessage?: string;
}

export interface BatchUpdateDetectorRequest {
  readonly detectors: [];
}

export interface BatchUpdateDetectorResponse {
  readonly batchUpdateDetectorErrorEntries?: [];
}

export interface CustomerAction {
  readonly actionName?: string;
  readonly snoozeActionConfiguration?: SnoozeActionConfiguration;
  readonly enableActionConfiguration?: EnableActionConfiguration;
  readonly disableActionConfiguration?: DisableActionConfiguration;
  readonly acknowledgeActionConfiguration?: AcknowledgeActionConfiguration;
  readonly resetActionConfiguration?: ResetActionConfiguration;
}

export interface DescribeAlarmRequest {
  readonly alarmModelName: string;
  readonly keyValue?: string;
}

export interface DescribeAlarmResponse {
  readonly alarm?: Alarm;
}

export interface DescribeDetectorRequest {
  readonly detectorModelName: string;
  readonly keyValue?: string;
}

export interface DescribeDetectorResponse {
  readonly detector?: Detector;
}

export interface Detector {
  readonly detectorModelName?: string;
  readonly keyValue?: string;
  readonly detectorModelVersion?: string;
  readonly state?: DetectorState;
  readonly creationTime?: Date;
  readonly lastUpdateTime?: Date;
}

export interface DetectorState {
  readonly stateName: string;
  readonly variables: [];
  readonly timers: [];
}

export interface DetectorStateDefinition {
  readonly stateName: string;
  readonly variables: [];
  readonly timers: [];
}

export interface DetectorStateSummary {
  readonly stateName?: string;
}

export interface DetectorSummary {
  readonly detectorModelName?: string;
  readonly keyValue?: string;
  readonly detectorModelVersion?: string;
  readonly state?: DetectorStateSummary;
  readonly creationTime?: Date;
  readonly lastUpdateTime?: Date;
}

export interface DisableActionConfiguration {
  readonly note?: string;
}

export interface DisableAlarmActionRequest {
  readonly requestId: string;
  readonly alarmModelName: string;
  readonly keyValue?: string;
  readonly note?: string;
}

export interface EnableActionConfiguration {
  readonly note?: string;
}

export interface EnableAlarmActionRequest {
  readonly requestId: string;
  readonly alarmModelName: string;
  readonly keyValue?: string;
  readonly note?: string;
}

export interface InternalFailureException {
  readonly message?: string;
}

export interface InvalidRequestException {
  readonly message?: string;
}

export interface ListAlarmsRequest {
  readonly alarmModelName: string;
  readonly nextToken?: string;
  readonly maxResults?: number;
}

export interface ListAlarmsResponse {
  readonly alarmSummaries?: [];
  readonly nextToken?: string;
}

export interface ListDetectorsRequest {
  readonly detectorModelName: string;
  readonly stateName?: string;
  readonly nextToken?: string;
  readonly maxResults?: number;
}

export interface ListDetectorsResponse {
  readonly detectorSummaries?: [];
  readonly nextToken?: string;
}

export interface Message {
  readonly messageId: string;
  readonly inputName: string;
  readonly payload: unknown;
  readonly timestamp?: TimestampValue;
}

export interface ResetActionConfiguration {
  readonly note?: string;
}

export interface ResetAlarmActionRequest {
  readonly requestId: string;
  readonly alarmModelName: string;
  readonly keyValue?: string;
  readonly note?: string;
}

export interface ResourceNotFoundException {
  readonly message?: string;
}

export interface RuleEvaluation {
  readonly simpleRuleEvaluation?: SimpleRuleEvaluation;
}

export interface ServiceUnavailableException {
  readonly message?: string;
}

export interface SimpleRuleEvaluation {
  readonly inputPropertyValue?: string;
  readonly operator?: string;
  readonly thresholdValue?: string;
}

export interface SnoozeActionConfiguration {
  readonly snoozeDuration?: number;
  readonly note?: string;
}

export interface SnoozeAlarmActionRequest {
  readonly requestId: string;
  readonly alarmModelName: string;
  readonly keyValue?: string;
  readonly note?: string;
  readonly snoozeDuration: number;
}

export interface StateChangeConfiguration {
  readonly triggerType?: string;
}

export interface SystemEvent {
  readonly eventType?: string;
  readonly stateChangeConfiguration?: StateChangeConfiguration;
}

export interface ThrottlingException {
  readonly message?: string;
}

export interface Timer {
  readonly name: string;
  readonly timestamp: Date;
}

export interface TimerDefinition {
  readonly name: string;
  readonly seconds: number;
}

export interface TimestampValue {
  readonly timeInMillis?: number;
}

export interface UpdateDetectorRequest {
  readonly messageId: string;
  readonly detectorModelName: string;
  readonly keyValue?: string;
  readonly state: DetectorStateDefinition;
}

export interface Variable {
  readonly name: string;
  readonly value: string;
}

export interface VariableDefinition {
  readonly name: string;
  readonly value: string;
}


