/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface GetDeviceRegistration {
  readonly DeviceName: string;
  readonly DeviceFleetName: string;
}

export interface SendHeartbeat {
  readonly AgentMetrics?: [];
  readonly Models?: [];
  readonly AgentVersion: string;
  readonly DeviceName: string;
  readonly DeviceFleetName: string;
}

export interface EdgeMetric {
  readonly Dimension?: string;
  readonly MetricName?: string;
  readonly Value?: unknown;
  readonly Timestamp?: Date;
}

export interface GetDeviceRegistrationRequest {
  readonly DeviceName: string;
  readonly DeviceFleetName: string;
}

export interface GetDeviceRegistrationResult {
  readonly DeviceRegistration?: string;
  readonly CacheTTL?: string;
}

export interface InternalServiceException {
  readonly Message?: string;
}

export interface Model {
  readonly ModelName?: string;
  readonly ModelVersion?: string;
  readonly LatestSampleTime?: Date;
  readonly LatestInference?: Date;
  readonly ModelMetrics?: [];
}

export interface SendHeartbeatRequest {
  readonly AgentMetrics?: [];
  readonly Models?: [];
  readonly AgentVersion: string;
  readonly DeviceName: string;
  readonly DeviceFleetName: string;
}


