/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface CloneReceiptRuleSet {
  readonly RuleSetName: string;
  readonly OriginalRuleSetName: string;
}

export interface CreateConfigurationSet {
  readonly ConfigurationSet: ConfigurationSet;
}

export interface CreateConfigurationSetEventDestination {
  readonly ConfigurationSetName: string;
  readonly EventDestination: EventDestination;
}

export interface CreateConfigurationSetTrackingOptions {
  readonly ConfigurationSetName: string;
  readonly TrackingOptions: TrackingOptions;
}

export interface CreateCustomVerificationEmailTemplate {
  readonly TemplateName: string;
  readonly FromEmailAddress: string;
  readonly TemplateSubject: string;
  readonly TemplateContent: string;
  readonly SuccessRedirectionURL: string;
  readonly FailureRedirectionURL: string;
}

export interface CreateReceiptFilter {
  readonly Filter: ReceiptFilter;
}

export interface CreateReceiptRule {
  readonly RuleSetName: string;
  readonly After?: string;
  readonly Rule: ReceiptRule;
}

export interface CreateReceiptRuleSet {
  readonly RuleSetName: string;
}

export interface CreateTemplate {
  readonly Template: Template;
}

export interface DeleteConfigurationSet {
  readonly ConfigurationSetName: string;
}

export interface DeleteConfigurationSetEventDestination {
  readonly ConfigurationSetName: string;
  readonly EventDestinationName: string;
}

export interface DeleteConfigurationSetTrackingOptions {
  readonly ConfigurationSetName: string;
}

export interface DeleteCustomVerificationEmailTemplate {
  readonly TemplateName: string;
}

export interface DeleteIdentity {
  readonly Identity: string;
}

export interface DeleteIdentityPolicy {
  readonly Identity: string;
  readonly PolicyName: string;
}

export interface DeleteReceiptFilter {
  readonly FilterName: string;
}

export interface DeleteReceiptRule {
  readonly RuleSetName: string;
  readonly RuleName: string;
}

export interface DeleteReceiptRuleSet {
  readonly RuleSetName: string;
}

export interface DeleteTemplate {
  readonly TemplateName: string;
}

export interface DeleteVerifiedEmailAddress {
  readonly EmailAddress: string;
}

export interface DescribeActiveReceiptRuleSet {
}

export interface DescribeConfigurationSet {
  readonly ConfigurationSetName: string;
  readonly ConfigurationSetAttributeNames?: [];
}

export interface DescribeReceiptRule {
  readonly RuleSetName: string;
  readonly RuleName: string;
}

export interface DescribeReceiptRuleSet {
  readonly RuleSetName: string;
}

export interface GetCustomVerificationEmailTemplate {
  readonly TemplateName: string;
}

export interface GetIdentityDkimAttributes {
  readonly Identities: [];
}

export interface GetIdentityMailFromDomainAttributes {
  readonly Identities: [];
}

export interface GetIdentityNotificationAttributes {
  readonly Identities: [];
}

export interface GetIdentityPolicies {
  readonly Identity: string;
  readonly PolicyNames: [];
}

export interface GetIdentityVerificationAttributes {
  readonly Identities: [];
}

export interface GetTemplate {
  readonly TemplateName: string;
}

export interface ListConfigurationSets {
  readonly NextToken?: string;
  readonly MaxItems?: number;
}

export interface ListCustomVerificationEmailTemplates {
  readonly NextToken?: string;
  readonly MaxResults?: number;
}

export interface ListIdentities {
  readonly IdentityType?: string;
  readonly NextToken?: string;
  readonly MaxItems?: number;
}

export interface ListIdentityPolicies {
  readonly Identity: string;
}

export interface ListReceiptFilters {
}

export interface ListReceiptRuleSets {
  readonly NextToken?: string;
}

export interface ListTemplates {
  readonly NextToken?: string;
  readonly MaxItems?: number;
}

export interface PutConfigurationSetDeliveryOptions {
  readonly ConfigurationSetName: string;
  readonly DeliveryOptions?: DeliveryOptions;
}

export interface PutIdentityPolicy {
  readonly Identity: string;
  readonly PolicyName: string;
  readonly Policy: string;
}

export interface ReorderReceiptRuleSet {
  readonly RuleSetName: string;
  readonly RuleNames: [];
}

export interface SendBounce {
  readonly OriginalMessageId: string;
  readonly BounceSender: string;
  readonly Explanation?: string;
  readonly MessageDsn?: MessageDsn;
  readonly BouncedRecipientInfoList: [];
  readonly BounceSenderArn?: string;
}

export interface SendBulkTemplatedEmail {
  readonly Source: string;
  readonly SourceArn?: string;
  readonly ReplyToAddresses?: [];
  readonly ReturnPath?: string;
  readonly ReturnPathArn?: string;
  readonly ConfigurationSetName?: string;
  readonly DefaultTags?: [];
  readonly Template: string;
  readonly TemplateArn?: string;
  readonly DefaultTemplateData?: string;
  readonly Destinations: [];
}

export interface SendCustomVerificationEmail {
  readonly EmailAddress: string;
  readonly TemplateName: string;
  readonly ConfigurationSetName?: string;
}

export interface SendEmail {
  readonly Source: string;
  readonly Destination: Destination;
  readonly Message: Message;
  readonly ReplyToAddresses?: [];
  readonly ReturnPath?: string;
  readonly SourceArn?: string;
  readonly ReturnPathArn?: string;
  readonly Tags?: [];
  readonly ConfigurationSetName?: string;
}

export interface SendRawEmail {
  readonly Source?: string;
  readonly Destinations?: [];
  readonly RawMessage: RawMessage;
  readonly FromArn?: string;
  readonly SourceArn?: string;
  readonly ReturnPathArn?: string;
  readonly Tags?: [];
  readonly ConfigurationSetName?: string;
}

export interface SendTemplatedEmail {
  readonly Source: string;
  readonly Destination: Destination;
  readonly ReplyToAddresses?: [];
  readonly ReturnPath?: string;
  readonly SourceArn?: string;
  readonly ReturnPathArn?: string;
  readonly Tags?: [];
  readonly ConfigurationSetName?: string;
  readonly Template: string;
  readonly TemplateArn?: string;
  readonly TemplateData: string;
}

export interface SetActiveReceiptRuleSet {
  readonly RuleSetName?: string;
}

export interface SetIdentityDkimEnabled {
  readonly Identity: string;
  readonly DkimEnabled: boolean;
}

export interface SetIdentityFeedbackForwardingEnabled {
  readonly Identity: string;
  readonly ForwardingEnabled: boolean;
}

export interface SetIdentityHeadersInNotificationsEnabled {
  readonly Identity: string;
  readonly NotificationType: string;
  readonly Enabled: boolean;
}

export interface SetIdentityMailFromDomain {
  readonly Identity: string;
  readonly MailFromDomain?: string;
  readonly BehaviorOnMXFailure?: string;
}

export interface SetIdentityNotificationTopic {
  readonly Identity: string;
  readonly NotificationType: string;
  readonly SnsTopic?: string;
}

export interface SetReceiptRulePosition {
  readonly RuleSetName: string;
  readonly RuleName: string;
  readonly After?: string;
}

export interface TestRenderTemplate {
  readonly TemplateName: string;
  readonly TemplateData: string;
}

export interface UpdateAccountSendingEnabled {
  readonly Enabled?: boolean;
}

export interface UpdateConfigurationSetEventDestination {
  readonly ConfigurationSetName: string;
  readonly EventDestination: EventDestination;
}

export interface UpdateConfigurationSetReputationMetricsEnabled {
  readonly ConfigurationSetName: string;
  readonly Enabled: boolean;
}

export interface UpdateConfigurationSetSendingEnabled {
  readonly ConfigurationSetName: string;
  readonly Enabled: boolean;
}

export interface UpdateConfigurationSetTrackingOptions {
  readonly ConfigurationSetName: string;
  readonly TrackingOptions: TrackingOptions;
}

export interface UpdateCustomVerificationEmailTemplate {
  readonly TemplateName: string;
  readonly FromEmailAddress?: string;
  readonly TemplateSubject?: string;
  readonly TemplateContent?: string;
  readonly SuccessRedirectionURL?: string;
  readonly FailureRedirectionURL?: string;
}

export interface UpdateReceiptRule {
  readonly RuleSetName: string;
  readonly Rule: ReceiptRule;
}

export interface UpdateTemplate {
  readonly Template: Template;
}

export interface VerifyDomainDkim {
  readonly Domain: string;
}

export interface VerifyDomainIdentity {
  readonly Domain: string;
}

export interface VerifyEmailAddress {
  readonly EmailAddress: string;
}

export interface VerifyEmailIdentity {
  readonly EmailAddress: string;
}

export interface AccountSendingPausedException {
}

export interface AddHeaderAction {
  readonly HeaderName: string;
  readonly HeaderValue: string;
}

export interface AlreadyExistsException {
  readonly Name?: string;
}

export interface Body {
  readonly Text?: Content;
  readonly Html?: Content;
}

export interface BounceAction {
  readonly TopicArn?: string;
  readonly SmtpReplyCode: string;
  readonly StatusCode?: string;
  readonly Message: string;
  readonly Sender: string;
}

export interface BouncedRecipientInfo {
  readonly Recipient: string;
  readonly RecipientArn?: string;
  readonly BounceType?: string;
  readonly RecipientDsnFields?: RecipientDsnFields;
}

export interface BulkEmailDestination {
  readonly Destination: Destination;
  readonly ReplacementTags?: [];
  readonly ReplacementTemplateData?: string;
}

export interface BulkEmailDestinationStatus {
  readonly Status?: string;
  readonly Error?: string;
  readonly MessageId?: string;
}

export interface CannotDeleteException {
  readonly Name?: string;
}

export interface CloneReceiptRuleSetRequest {
  readonly RuleSetName: string;
  readonly OriginalRuleSetName: string;
}

export interface CloneReceiptRuleSetResponse {
}

export interface CloudWatchDestination {
  readonly DimensionConfigurations: [];
}

export interface CloudWatchDimensionConfiguration {
  readonly DimensionName: string;
  readonly DimensionValueSource: string;
  readonly DefaultDimensionValue: string;
}

export interface ConfigurationSet {
  readonly Name: string;
}

export interface ConfigurationSetAlreadyExistsException {
  readonly ConfigurationSetName?: string;
}

export interface ConfigurationSetDoesNotExistException {
  readonly ConfigurationSetName?: string;
}

export interface ConfigurationSetSendingPausedException {
  readonly ConfigurationSetName?: string;
}

export interface Content {
  readonly Data: string;
  readonly Charset?: string;
}

export interface CreateConfigurationSetEventDestinationRequest {
  readonly ConfigurationSetName: string;
  readonly EventDestination: EventDestination;
}

export interface CreateConfigurationSetEventDestinationResponse {
}

export interface CreateConfigurationSetRequest {
  readonly ConfigurationSet: ConfigurationSet;
}

export interface CreateConfigurationSetResponse {
}

export interface CreateConfigurationSetTrackingOptionsRequest {
  readonly ConfigurationSetName: string;
  readonly TrackingOptions: TrackingOptions;
}

export interface CreateConfigurationSetTrackingOptionsResponse {
}

export interface CreateCustomVerificationEmailTemplateRequest {
  readonly TemplateName: string;
  readonly FromEmailAddress: string;
  readonly TemplateSubject: string;
  readonly TemplateContent: string;
  readonly SuccessRedirectionURL: string;
  readonly FailureRedirectionURL: string;
}

export interface CreateReceiptFilterRequest {
  readonly Filter: ReceiptFilter;
}

export interface CreateReceiptFilterResponse {
}

export interface CreateReceiptRuleRequest {
  readonly RuleSetName: string;
  readonly After?: string;
  readonly Rule: ReceiptRule;
}

export interface CreateReceiptRuleResponse {
}

export interface CreateReceiptRuleSetRequest {
  readonly RuleSetName: string;
}

export interface CreateReceiptRuleSetResponse {
}

export interface CreateTemplateRequest {
  readonly Template: Template;
}

export interface CreateTemplateResponse {
}

export interface CustomVerificationEmailInvalidContentException {
}

export interface CustomVerificationEmailTemplate {
  readonly TemplateName?: string;
  readonly FromEmailAddress?: string;
  readonly TemplateSubject?: string;
  readonly SuccessRedirectionURL?: string;
  readonly FailureRedirectionURL?: string;
}

export interface CustomVerificationEmailTemplateAlreadyExistsException {
  readonly CustomVerificationEmailTemplateName?: string;
}

export interface CustomVerificationEmailTemplateDoesNotExistException {
  readonly CustomVerificationEmailTemplateName?: string;
}

export interface DeleteConfigurationSetEventDestinationRequest {
  readonly ConfigurationSetName: string;
  readonly EventDestinationName: string;
}

export interface DeleteConfigurationSetEventDestinationResponse {
}

export interface DeleteConfigurationSetRequest {
  readonly ConfigurationSetName: string;
}

export interface DeleteConfigurationSetResponse {
}

export interface DeleteConfigurationSetTrackingOptionsRequest {
  readonly ConfigurationSetName: string;
}

export interface DeleteConfigurationSetTrackingOptionsResponse {
}

export interface DeleteCustomVerificationEmailTemplateRequest {
  readonly TemplateName: string;
}

export interface DeleteIdentityPolicyRequest {
  readonly Identity: string;
  readonly PolicyName: string;
}

export interface DeleteIdentityPolicyResponse {
}

export interface DeleteIdentityRequest {
  readonly Identity: string;
}

export interface DeleteIdentityResponse {
}

export interface DeleteReceiptFilterRequest {
  readonly FilterName: string;
}

export interface DeleteReceiptFilterResponse {
}

export interface DeleteReceiptRuleRequest {
  readonly RuleSetName: string;
  readonly RuleName: string;
}

export interface DeleteReceiptRuleResponse {
}

export interface DeleteReceiptRuleSetRequest {
  readonly RuleSetName: string;
}

export interface DeleteReceiptRuleSetResponse {
}

export interface DeleteTemplateRequest {
  readonly TemplateName: string;
}

export interface DeleteTemplateResponse {
}

export interface DeleteVerifiedEmailAddressRequest {
  readonly EmailAddress: string;
}

export interface DeliveryOptions {
  readonly TlsPolicy?: string;
}

export interface DescribeActiveReceiptRuleSetRequest {
}

export interface DescribeActiveReceiptRuleSetResponse {
  readonly Metadata?: ReceiptRuleSetMetadata;
  readonly Rules?: [];
}

export interface DescribeConfigurationSetRequest {
  readonly ConfigurationSetName: string;
  readonly ConfigurationSetAttributeNames?: [];
}

export interface DescribeConfigurationSetResponse {
  readonly ConfigurationSet?: ConfigurationSet;
  readonly EventDestinations?: [];
  readonly TrackingOptions?: TrackingOptions;
  readonly DeliveryOptions?: DeliveryOptions;
  readonly ReputationOptions?: ReputationOptions;
}

export interface DescribeReceiptRuleRequest {
  readonly RuleSetName: string;
  readonly RuleName: string;
}

export interface DescribeReceiptRuleResponse {
  readonly Rule?: ReceiptRule;
}

export interface DescribeReceiptRuleSetRequest {
  readonly RuleSetName: string;
}

export interface DescribeReceiptRuleSetResponse {
  readonly Metadata?: ReceiptRuleSetMetadata;
  readonly Rules?: [];
}

export interface Destination {
  readonly ToAddresses?: [];
  readonly CcAddresses?: [];
  readonly BccAddresses?: [];
}

export interface EventDestination {
  readonly Name: string;
  readonly Enabled?: boolean;
  readonly MatchingEventTypes: [];
  readonly KinesisFirehoseDestination?: KinesisFirehoseDestination;
  readonly CloudWatchDestination?: CloudWatchDestination;
  readonly SNSDestination?: SNSDestination;
}

export interface EventDestinationAlreadyExistsException {
  readonly ConfigurationSetName?: string;
  readonly EventDestinationName?: string;
}

export interface EventDestinationDoesNotExistException {
  readonly ConfigurationSetName?: string;
  readonly EventDestinationName?: string;
}

export interface ExtensionField {
  readonly Name: string;
  readonly Value: string;
}

export interface FromEmailAddressNotVerifiedException {
  readonly FromEmailAddress?: string;
}

export interface GetAccountSendingEnabledResponse {
  readonly Enabled?: boolean;
}

export interface GetCustomVerificationEmailTemplateRequest {
  readonly TemplateName: string;
}

export interface GetCustomVerificationEmailTemplateResponse {
  readonly TemplateName?: string;
  readonly FromEmailAddress?: string;
  readonly TemplateSubject?: string;
  readonly TemplateContent?: string;
  readonly SuccessRedirectionURL?: string;
  readonly FailureRedirectionURL?: string;
}

export interface GetIdentityDkimAttributesRequest {
  readonly Identities: [];
}

export interface GetIdentityDkimAttributesResponse {
  readonly DkimAttributes: {[key: string]: any};
}

export interface GetIdentityMailFromDomainAttributesRequest {
  readonly Identities: [];
}

export interface GetIdentityMailFromDomainAttributesResponse {
  readonly MailFromDomainAttributes: {[key: string]: any};
}

export interface GetIdentityNotificationAttributesRequest {
  readonly Identities: [];
}

export interface GetIdentityNotificationAttributesResponse {
  readonly NotificationAttributes: {[key: string]: any};
}

export interface GetIdentityPoliciesRequest {
  readonly Identity: string;
  readonly PolicyNames: [];
}

export interface GetIdentityPoliciesResponse {
  readonly Policies: {[key: string]: any};
}

export interface GetIdentityVerificationAttributesRequest {
  readonly Identities: [];
}

export interface GetIdentityVerificationAttributesResponse {
  readonly VerificationAttributes: {[key: string]: any};
}

export interface GetSendQuotaResponse {
  readonly Max24HourSend?: unknown;
  readonly MaxSendRate?: unknown;
  readonly SentLast24Hours?: unknown;
}

export interface GetSendStatisticsResponse {
  readonly SendDataPoints?: [];
}

export interface GetTemplateRequest {
  readonly TemplateName: string;
}

export interface GetTemplateResponse {
  readonly Template?: Template;
}

export interface IdentityDkimAttributes {
  readonly DkimEnabled: boolean;
  readonly DkimVerificationStatus: string;
  readonly DkimTokens?: [];
}

export interface IdentityMailFromDomainAttributes {
  readonly MailFromDomain: string;
  readonly MailFromDomainStatus: string;
  readonly BehaviorOnMXFailure: string;
}

export interface IdentityNotificationAttributes {
  readonly BounceTopic: string;
  readonly ComplaintTopic: string;
  readonly DeliveryTopic: string;
  readonly ForwardingEnabled: boolean;
  readonly HeadersInBounceNotificationsEnabled?: boolean;
  readonly HeadersInComplaintNotificationsEnabled?: boolean;
  readonly HeadersInDeliveryNotificationsEnabled?: boolean;
}

export interface IdentityVerificationAttributes {
  readonly VerificationStatus: string;
  readonly VerificationToken?: string;
}

export interface InvalidCloudWatchDestinationException {
  readonly ConfigurationSetName?: string;
  readonly EventDestinationName?: string;
}

export interface InvalidConfigurationSetException {
}

export interface InvalidDeliveryOptionsException {
}

export interface InvalidFirehoseDestinationException {
  readonly ConfigurationSetName?: string;
  readonly EventDestinationName?: string;
}

export interface InvalidLambdaFunctionException {
  readonly FunctionArn?: string;
}

export interface InvalidPolicyException {
}

export interface InvalidRenderingParameterException {
  readonly TemplateName?: string;
}

export interface InvalidS3ConfigurationException {
  readonly Bucket?: string;
}

export interface InvalidSNSDestinationException {
  readonly ConfigurationSetName?: string;
  readonly EventDestinationName?: string;
}

export interface InvalidSnsTopicException {
  readonly Topic?: string;
}

export interface InvalidTemplateException {
  readonly TemplateName?: string;
}

export interface InvalidTrackingOptionsException {
}

export interface KinesisFirehoseDestination {
  readonly IAMRoleARN: string;
  readonly DeliveryStreamARN: string;
}

export interface LambdaAction {
  readonly TopicArn?: string;
  readonly FunctionArn: string;
  readonly InvocationType?: string;
}

export interface LimitExceededException {
}

export interface ListConfigurationSetsRequest {
  readonly NextToken?: string;
  readonly MaxItems?: number;
}

export interface ListConfigurationSetsResponse {
  readonly ConfigurationSets?: [];
  readonly NextToken?: string;
}

export interface ListCustomVerificationEmailTemplatesRequest {
  readonly NextToken?: string;
  readonly MaxResults?: number;
}

export interface ListCustomVerificationEmailTemplatesResponse {
  readonly CustomVerificationEmailTemplates?: [];
  readonly NextToken?: string;
}

export interface ListIdentitiesRequest {
  readonly IdentityType?: string;
  readonly NextToken?: string;
  readonly MaxItems?: number;
}

export interface ListIdentitiesResponse {
  readonly Identities: [];
  readonly NextToken?: string;
}

export interface ListIdentityPoliciesRequest {
  readonly Identity: string;
}

export interface ListIdentityPoliciesResponse {
  readonly PolicyNames: [];
}

export interface ListReceiptFiltersRequest {
}

export interface ListReceiptFiltersResponse {
  readonly Filters?: [];
}

export interface ListReceiptRuleSetsRequest {
  readonly NextToken?: string;
}

export interface ListReceiptRuleSetsResponse {
  readonly RuleSets?: [];
  readonly NextToken?: string;
}

export interface ListTemplatesRequest {
  readonly NextToken?: string;
  readonly MaxItems?: number;
}

export interface ListTemplatesResponse {
  readonly TemplatesMetadata?: [];
  readonly NextToken?: string;
}

export interface ListVerifiedEmailAddressesResponse {
  readonly VerifiedEmailAddresses?: [];
}

export interface MailFromDomainNotVerifiedException {
}

export interface Message {
  readonly Subject: Content;
  readonly Body: Body;
}

export interface MessageDsn {
  readonly ReportingMta: string;
  readonly ArrivalDate?: Date;
  readonly ExtensionFields?: [];
}

export interface MessageRejected {
}

export interface MessageTag {
  readonly Name: string;
  readonly Value: string;
}

export interface MissingRenderingAttributeException {
  readonly TemplateName?: string;
}

export interface ProductionAccessNotGrantedException {
}

export interface PutConfigurationSetDeliveryOptionsRequest {
  readonly ConfigurationSetName: string;
  readonly DeliveryOptions?: DeliveryOptions;
}

export interface PutConfigurationSetDeliveryOptionsResponse {
}

export interface PutIdentityPolicyRequest {
  readonly Identity: string;
  readonly PolicyName: string;
  readonly Policy: string;
}

export interface PutIdentityPolicyResponse {
}

export interface RawMessage {
  readonly Data: unknown;
}

export interface ReceiptAction {
  readonly S3Action?: S3Action;
  readonly BounceAction?: BounceAction;
  readonly WorkmailAction?: WorkmailAction;
  readonly LambdaAction?: LambdaAction;
  readonly StopAction?: StopAction;
  readonly AddHeaderAction?: AddHeaderAction;
  readonly SNSAction?: SNSAction;
}

export interface ReceiptFilter {
  readonly Name: string;
  readonly IpFilter: ReceiptIpFilter;
}

export interface ReceiptIpFilter {
  readonly Policy: string;
  readonly Cidr: string;
}

export interface ReceiptRule {
  readonly Name: string;
  readonly Enabled?: boolean;
  readonly TlsPolicy?: string;
  readonly Recipients?: [];
  readonly Actions?: [];
  readonly ScanEnabled?: boolean;
}

export interface ReceiptRuleSetMetadata {
  readonly Name?: string;
  readonly CreatedTimestamp?: Date;
}

export interface RecipientDsnFields {
  readonly FinalRecipient?: string;
  readonly Action: string;
  readonly RemoteMta?: string;
  readonly Status: string;
  readonly DiagnosticCode?: string;
  readonly LastAttemptDate?: Date;
  readonly ExtensionFields?: [];
}

export interface ReorderReceiptRuleSetRequest {
  readonly RuleSetName: string;
  readonly RuleNames: [];
}

export interface ReorderReceiptRuleSetResponse {
}

export interface ReputationOptions {
  readonly SendingEnabled?: boolean;
  readonly ReputationMetricsEnabled?: boolean;
  readonly LastFreshStart?: Date;
}

export interface RuleDoesNotExistException {
  readonly Name?: string;
}

export interface RuleSetDoesNotExistException {
  readonly Name?: string;
}

export interface S3Action {
  readonly TopicArn?: string;
  readonly BucketName: string;
  readonly ObjectKeyPrefix?: string;
  readonly KmsKeyArn?: string;
}

export interface SNSAction {
  readonly TopicArn: string;
  readonly Encoding?: string;
}

export interface SNSDestination {
  readonly TopicARN: string;
}

export interface SendBounceRequest {
  readonly OriginalMessageId: string;
  readonly BounceSender: string;
  readonly Explanation?: string;
  readonly MessageDsn?: MessageDsn;
  readonly BouncedRecipientInfoList: [];
  readonly BounceSenderArn?: string;
}

export interface SendBounceResponse {
  readonly MessageId?: string;
}

export interface SendBulkTemplatedEmailRequest {
  readonly Source: string;
  readonly SourceArn?: string;
  readonly ReplyToAddresses?: [];
  readonly ReturnPath?: string;
  readonly ReturnPathArn?: string;
  readonly ConfigurationSetName?: string;
  readonly DefaultTags?: [];
  readonly Template: string;
  readonly TemplateArn?: string;
  readonly DefaultTemplateData?: string;
  readonly Destinations: [];
}

export interface SendBulkTemplatedEmailResponse {
  readonly Status: [];
}

export interface SendCustomVerificationEmailRequest {
  readonly EmailAddress: string;
  readonly TemplateName: string;
  readonly ConfigurationSetName?: string;
}

export interface SendCustomVerificationEmailResponse {
  readonly MessageId?: string;
}

export interface SendDataPoint {
  readonly Timestamp?: Date;
  readonly DeliveryAttempts?: number;
  readonly Bounces?: number;
  readonly Complaints?: number;
  readonly Rejects?: number;
}

export interface SendEmailRequest {
  readonly Source: string;
  readonly Destination: Destination;
  readonly Message: Message;
  readonly ReplyToAddresses?: [];
  readonly ReturnPath?: string;
  readonly SourceArn?: string;
  readonly ReturnPathArn?: string;
  readonly Tags?: [];
  readonly ConfigurationSetName?: string;
}

export interface SendEmailResponse {
  readonly MessageId: string;
}

export interface SendRawEmailRequest {
  readonly Source?: string;
  readonly Destinations?: [];
  readonly RawMessage: RawMessage;
  readonly FromArn?: string;
  readonly SourceArn?: string;
  readonly ReturnPathArn?: string;
  readonly Tags?: [];
  readonly ConfigurationSetName?: string;
}

export interface SendRawEmailResponse {
  readonly MessageId: string;
}

export interface SendTemplatedEmailRequest {
  readonly Source: string;
  readonly Destination: Destination;
  readonly ReplyToAddresses?: [];
  readonly ReturnPath?: string;
  readonly SourceArn?: string;
  readonly ReturnPathArn?: string;
  readonly Tags?: [];
  readonly ConfigurationSetName?: string;
  readonly Template: string;
  readonly TemplateArn?: string;
  readonly TemplateData: string;
}

export interface SendTemplatedEmailResponse {
  readonly MessageId: string;
}

export interface SetActiveReceiptRuleSetRequest {
  readonly RuleSetName?: string;
}

export interface SetActiveReceiptRuleSetResponse {
}

export interface SetIdentityDkimEnabledRequest {
  readonly Identity: string;
  readonly DkimEnabled: boolean;
}

export interface SetIdentityDkimEnabledResponse {
}

export interface SetIdentityFeedbackForwardingEnabledRequest {
  readonly Identity: string;
  readonly ForwardingEnabled: boolean;
}

export interface SetIdentityFeedbackForwardingEnabledResponse {
}

export interface SetIdentityHeadersInNotificationsEnabledRequest {
  readonly Identity: string;
  readonly NotificationType: string;
  readonly Enabled: boolean;
}

export interface SetIdentityHeadersInNotificationsEnabledResponse {
}

export interface SetIdentityMailFromDomainRequest {
  readonly Identity: string;
  readonly MailFromDomain?: string;
  readonly BehaviorOnMXFailure?: string;
}

export interface SetIdentityMailFromDomainResponse {
}

export interface SetIdentityNotificationTopicRequest {
  readonly Identity: string;
  readonly NotificationType: string;
  readonly SnsTopic?: string;
}

export interface SetIdentityNotificationTopicResponse {
}

export interface SetReceiptRulePositionRequest {
  readonly RuleSetName: string;
  readonly RuleName: string;
  readonly After?: string;
}

export interface SetReceiptRulePositionResponse {
}

export interface StopAction {
  readonly Scope: string;
  readonly TopicArn?: string;
}

export interface Template {
  readonly TemplateName: string;
  readonly SubjectPart?: string;
  readonly TextPart?: string;
  readonly HtmlPart?: string;
}

export interface TemplateDoesNotExistException {
  readonly TemplateName?: string;
}

export interface TemplateMetadata {
  readonly Name?: string;
  readonly CreatedTimestamp?: Date;
}

export interface TestRenderTemplateRequest {
  readonly TemplateName: string;
  readonly TemplateData: string;
}

export interface TestRenderTemplateResponse {
  readonly RenderedTemplate?: string;
}

export interface TrackingOptions {
  readonly CustomRedirectDomain?: string;
}

export interface TrackingOptionsAlreadyExistsException {
  readonly ConfigurationSetName?: string;
}

export interface TrackingOptionsDoesNotExistException {
  readonly ConfigurationSetName?: string;
}

export interface UpdateAccountSendingEnabledRequest {
  readonly Enabled?: boolean;
}

export interface UpdateConfigurationSetEventDestinationRequest {
  readonly ConfigurationSetName: string;
  readonly EventDestination: EventDestination;
}

export interface UpdateConfigurationSetEventDestinationResponse {
}

export interface UpdateConfigurationSetReputationMetricsEnabledRequest {
  readonly ConfigurationSetName: string;
  readonly Enabled: boolean;
}

export interface UpdateConfigurationSetSendingEnabledRequest {
  readonly ConfigurationSetName: string;
  readonly Enabled: boolean;
}

export interface UpdateConfigurationSetTrackingOptionsRequest {
  readonly ConfigurationSetName: string;
  readonly TrackingOptions: TrackingOptions;
}

export interface UpdateConfigurationSetTrackingOptionsResponse {
}

export interface UpdateCustomVerificationEmailTemplateRequest {
  readonly TemplateName: string;
  readonly FromEmailAddress?: string;
  readonly TemplateSubject?: string;
  readonly TemplateContent?: string;
  readonly SuccessRedirectionURL?: string;
  readonly FailureRedirectionURL?: string;
}

export interface UpdateReceiptRuleRequest {
  readonly RuleSetName: string;
  readonly Rule: ReceiptRule;
}

export interface UpdateReceiptRuleResponse {
}

export interface UpdateTemplateRequest {
  readonly Template: Template;
}

export interface UpdateTemplateResponse {
}

export interface VerifyDomainDkimRequest {
  readonly Domain: string;
}

export interface VerifyDomainDkimResponse {
  readonly DkimTokens: [];
}

export interface VerifyDomainIdentityRequest {
  readonly Domain: string;
}

export interface VerifyDomainIdentityResponse {
  readonly VerificationToken: string;
}

export interface VerifyEmailAddressRequest {
  readonly EmailAddress: string;
}

export interface VerifyEmailIdentityRequest {
  readonly EmailAddress: string;
}

export interface VerifyEmailIdentityResponse {
}

export interface WorkmailAction {
  readonly TopicArn?: string;
  readonly OrganizationArn: string;
}


