/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface CancelContact {
  readonly contactId: string;
}

export interface CreateConfig {
  readonly configData: ConfigTypeData;
  readonly name: string;
  readonly tags?: {[key: string]: any};
}

export interface CreateDataflowEndpointGroup {
  readonly endpointDetails: [];
  readonly tags?: {[key: string]: any};
}

export interface CreateMissionProfile {
  readonly contactPostPassDurationSeconds?: number;
  readonly contactPrePassDurationSeconds?: number;
  readonly dataflowEdges: [];
  readonly minimumViableContactDurationSeconds: number;
  readonly name: string;
  readonly tags?: {[key: string]: any};
  readonly trackingConfigArn: string;
}

export interface DeleteConfig {
  readonly configId: string;
  readonly configType: string;
}

export interface DeleteDataflowEndpointGroup {
  readonly dataflowEndpointGroupId: string;
}

export interface DeleteMissionProfile {
  readonly missionProfileId: string;
}

export interface DescribeContact {
  readonly contactId: string;
}

export interface GetConfig {
  readonly configId: string;
  readonly configType: string;
}

export interface GetDataflowEndpointGroup {
  readonly dataflowEndpointGroupId: string;
}

export interface GetMinuteUsage {
  readonly month: number;
  readonly year: number;
}

export interface GetMissionProfile {
  readonly missionProfileId: string;
}

export interface GetSatellite {
  readonly satelliteId: string;
}

export interface ListConfigs {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListContacts {
  readonly endTime: Date;
  readonly groundStation?: string;
  readonly maxResults?: number;
  readonly missionProfileArn?: string;
  readonly nextToken?: string;
  readonly satelliteArn?: string;
  readonly startTime: Date;
  readonly statusList: [];
}

export interface ListDataflowEndpointGroups {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListGroundStations {
  readonly maxResults?: number;
  readonly nextToken?: string;
  readonly satelliteId?: string;
}

export interface ListMissionProfiles {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListSatellites {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListTagsForResource {
  readonly resourceArn: string;
}

export interface ReserveContact {
  readonly endTime: Date;
  readonly groundStation: string;
  readonly missionProfileArn: string;
  readonly satelliteArn: string;
  readonly startTime: Date;
  readonly tags?: {[key: string]: any};
}

export interface TagResource {
  readonly resourceArn: string;
  readonly tags: {[key: string]: any};
}

export interface UntagResource {
  readonly resourceArn: string;
  readonly tagKeys: [];
}

export interface UpdateConfig {
  readonly configData: ConfigTypeData;
  readonly configId: string;
  readonly configType: string;
  readonly name: string;
}

export interface UpdateMissionProfile {
  readonly contactPostPassDurationSeconds?: number;
  readonly contactPrePassDurationSeconds?: number;
  readonly dataflowEdges?: [];
  readonly minimumViableContactDurationSeconds?: number;
  readonly missionProfileId: string;
  readonly name?: string;
  readonly trackingConfigArn?: string;
}

export interface AntennaDemodDecodeDetails {
  readonly outputNode?: string;
}

export interface AntennaDownlinkConfig {
  readonly spectrumConfig: SpectrumConfig;
}

export interface AntennaDownlinkDemodDecodeConfig {
  readonly decodeConfig: DecodeConfig;
  readonly demodulationConfig: DemodulationConfig;
  readonly spectrumConfig: SpectrumConfig;
}

export interface AntennaUplinkConfig {
  readonly spectrumConfig: UplinkSpectrumConfig;
  readonly targetEirp: Eirp;
  readonly transmitDisabled?: boolean;
}

export interface CancelContactRequest {
  readonly contactId: string;
}

export interface ConfigDetails {
  readonly antennaDemodDecodeDetails?: AntennaDemodDecodeDetails;
  readonly endpointDetails?: EndpointDetails;
  readonly s3RecordingDetails?: S3RecordingDetails;
}

export interface ConfigIdResponse {
  readonly configArn?: string;
  readonly configId?: string;
  readonly configType?: string;
}

export interface ConfigListItem {
  readonly configArn?: string;
  readonly configId?: string;
  readonly configType?: string;
  readonly name?: string;
}

export interface ConfigTypeData {
  readonly antennaDownlinkConfig?: AntennaDownlinkConfig;
  readonly antennaDownlinkDemodDecodeConfig?: AntennaDownlinkDemodDecodeConfig;
  readonly antennaUplinkConfig?: AntennaUplinkConfig;
  readonly dataflowEndpointConfig?: DataflowEndpointConfig;
  readonly s3RecordingConfig?: S3RecordingConfig;
  readonly trackingConfig?: TrackingConfig;
  readonly uplinkEchoConfig?: UplinkEchoConfig;
}

export interface ContactData {
  readonly contactId?: string;
  readonly contactStatus?: string;
  readonly endTime?: Date;
  readonly errorMessage?: string;
  readonly groundStation?: string;
  readonly maximumElevation?: Elevation;
  readonly missionProfileArn?: string;
  readonly postPassEndTime?: Date;
  readonly prePassStartTime?: Date;
  readonly region?: string;
  readonly satelliteArn?: string;
  readonly startTime?: Date;
  readonly tags?: {[key: string]: any};
}

export interface ContactIdResponse {
  readonly contactId?: string;
}

export interface CreateConfigRequest {
  readonly configData: ConfigTypeData;
  readonly name: string;
  readonly tags?: {[key: string]: any};
}

export interface CreateDataflowEndpointGroupRequest {
  readonly endpointDetails: [];
  readonly tags?: {[key: string]: any};
}

export interface CreateMissionProfileRequest {
  readonly contactPostPassDurationSeconds?: number;
  readonly contactPrePassDurationSeconds?: number;
  readonly dataflowEdges: [];
  readonly minimumViableContactDurationSeconds: number;
  readonly name: string;
  readonly tags?: {[key: string]: any};
  readonly trackingConfigArn: string;
}

export interface DataflowDetail {
  readonly destination?: Destination;
  readonly errorMessage?: string;
  readonly source?: Source;
}

export interface DataflowEndpoint {
  readonly address?: SocketAddress;
  readonly mtu?: number;
  readonly name?: string;
  readonly status?: string;
}

export interface DataflowEndpointConfig {
  readonly dataflowEndpointName: string;
  readonly dataflowEndpointRegion?: string;
}

export interface DataflowEndpointGroupIdResponse {
  readonly dataflowEndpointGroupId?: string;
}

export interface DataflowEndpointListItem {
  readonly dataflowEndpointGroupArn?: string;
  readonly dataflowEndpointGroupId?: string;
}

export interface DecodeConfig {
  readonly unvalidatedJSON: string;
}

export interface DeleteConfigRequest {
  readonly configId: string;
  readonly configType: string;
}

export interface DeleteDataflowEndpointGroupRequest {
  readonly dataflowEndpointGroupId: string;
}

export interface DeleteMissionProfileRequest {
  readonly missionProfileId: string;
}

export interface DemodulationConfig {
  readonly unvalidatedJSON: string;
}

export interface DependencyException {
  readonly message?: string;
  readonly parameterName?: string;
}

export interface DescribeContactRequest {
  readonly contactId: string;
}

export interface DescribeContactResponse {
  readonly contactId?: string;
  readonly contactStatus?: string;
  readonly dataflowList?: [];
  readonly endTime?: Date;
  readonly errorMessage?: string;
  readonly groundStation?: string;
  readonly maximumElevation?: Elevation;
  readonly missionProfileArn?: string;
  readonly postPassEndTime?: Date;
  readonly prePassStartTime?: Date;
  readonly region?: string;
  readonly satelliteArn?: string;
  readonly startTime?: Date;
  readonly tags?: {[key: string]: any};
}

export interface Destination {
  readonly configDetails?: ConfigDetails;
  readonly configId?: string;
  readonly configType?: string;
  readonly dataflowDestinationRegion?: string;
}

export interface Eirp {
  readonly units: string;
  readonly value: unknown;
}

export interface Elevation {
  readonly unit: string;
  readonly value: unknown;
}

export interface EndpointDetails {
  readonly endpoint?: DataflowEndpoint;
  readonly securityDetails?: SecurityDetails;
}

export interface Frequency {
  readonly units: string;
  readonly value: unknown;
}

export interface FrequencyBandwidth {
  readonly units: string;
  readonly value: unknown;
}

export interface GetConfigRequest {
  readonly configId: string;
  readonly configType: string;
}

export interface GetConfigResponse {
  readonly configArn: string;
  readonly configData: ConfigTypeData;
  readonly configId: string;
  readonly configType?: string;
  readonly name: string;
  readonly tags?: {[key: string]: any};
}

export interface GetDataflowEndpointGroupRequest {
  readonly dataflowEndpointGroupId: string;
}

export interface GetDataflowEndpointGroupResponse {
  readonly dataflowEndpointGroupArn?: string;
  readonly dataflowEndpointGroupId?: string;
  readonly endpointsDetails?: [];
  readonly tags?: {[key: string]: any};
}

export interface GetMinuteUsageRequest {
  readonly month: number;
  readonly year: number;
}

export interface GetMinuteUsageResponse {
  readonly estimatedMinutesRemaining?: number;
  readonly isReservedMinutesCustomer?: boolean;
  readonly totalReservedMinuteAllocation?: number;
  readonly totalScheduledMinutes?: number;
  readonly upcomingMinutesScheduled?: number;
}

export interface GetMissionProfileRequest {
  readonly missionProfileId: string;
}

export interface GetMissionProfileResponse {
  readonly contactPostPassDurationSeconds?: number;
  readonly contactPrePassDurationSeconds?: number;
  readonly dataflowEdges?: [];
  readonly minimumViableContactDurationSeconds?: number;
  readonly missionProfileArn?: string;
  readonly missionProfileId?: string;
  readonly name?: string;
  readonly region?: string;
  readonly tags?: {[key: string]: any};
  readonly trackingConfigArn?: string;
}

export interface GetSatelliteRequest {
  readonly satelliteId: string;
}

export interface GetSatelliteResponse {
  readonly groundStations?: [];
  readonly noradSatelliteID?: number;
  readonly satelliteArn?: string;
  readonly satelliteId?: string;
}

export interface GroundStationData {
  readonly groundStationId?: string;
  readonly groundStationName?: string;
  readonly region?: string;
}

export interface InvalidParameterException {
  readonly message?: string;
  readonly parameterName?: string;
}

export interface ListConfigsRequest {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListConfigsResponse {
  readonly configList?: [];
  readonly nextToken?: string;
}

export interface ListContactsRequest {
  readonly endTime: Date;
  readonly groundStation?: string;
  readonly maxResults?: number;
  readonly missionProfileArn?: string;
  readonly nextToken?: string;
  readonly satelliteArn?: string;
  readonly startTime: Date;
  readonly statusList: [];
}

export interface ListContactsResponse {
  readonly contactList?: [];
  readonly nextToken?: string;
}

export interface ListDataflowEndpointGroupsRequest {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListDataflowEndpointGroupsResponse {
  readonly dataflowEndpointGroupList?: [];
  readonly nextToken?: string;
}

export interface ListGroundStationsRequest {
  readonly maxResults?: number;
  readonly nextToken?: string;
  readonly satelliteId?: string;
}

export interface ListGroundStationsResponse {
  readonly groundStationList?: [];
  readonly nextToken?: string;
}

export interface ListMissionProfilesRequest {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListMissionProfilesResponse {
  readonly missionProfileList?: [];
  readonly nextToken?: string;
}

export interface ListSatellitesRequest {
  readonly maxResults?: number;
  readonly nextToken?: string;
}

export interface ListSatellitesResponse {
  readonly nextToken?: string;
  readonly satellites?: [];
}

export interface ListTagsForResourceRequest {
  readonly resourceArn: string;
}

export interface ListTagsForResourceResponse {
  readonly tags?: {[key: string]: any};
}

export interface MissionProfileIdResponse {
  readonly missionProfileId?: string;
}

export interface MissionProfileListItem {
  readonly missionProfileArn?: string;
  readonly missionProfileId?: string;
  readonly name?: string;
  readonly region?: string;
}

export interface ReserveContactRequest {
  readonly endTime: Date;
  readonly groundStation: string;
  readonly missionProfileArn: string;
  readonly satelliteArn: string;
  readonly startTime: Date;
  readonly tags?: {[key: string]: any};
}

export interface ResourceLimitExceededException {
  readonly message?: string;
  readonly parameterName?: string;
}

export interface ResourceNotFoundException {
  readonly message?: string;
}

export interface S3RecordingConfig {
  readonly bucketArn: string;
  readonly prefix?: string;
  readonly roleArn: string;
}

export interface S3RecordingDetails {
  readonly bucketArn?: string;
  readonly keyTemplate?: string;
}

export interface SatelliteListItem {
  readonly groundStations?: [];
  readonly noradSatelliteID?: number;
  readonly satelliteArn?: string;
  readonly satelliteId?: string;
}

export interface SecurityDetails {
  readonly roleArn: string;
  readonly securityGroupIds: [];
  readonly subnetIds: [];
}

export interface SocketAddress {
  readonly name: string;
  readonly port: number;
}

export interface Source {
  readonly configDetails?: ConfigDetails;
  readonly configId?: string;
  readonly configType?: string;
  readonly dataflowSourceRegion?: string;
}

export interface SpectrumConfig {
  readonly bandwidth: FrequencyBandwidth;
  readonly centerFrequency: Frequency;
  readonly polarization?: string;
}

export interface TagResourceRequest {
  readonly resourceArn: string;
  readonly tags: {[key: string]: any};
}

export interface TagResourceResponse {
}

export interface TrackingConfig {
  readonly autotrack: string;
}

export interface UntagResourceRequest {
  readonly resourceArn: string;
  readonly tagKeys: [];
}

export interface UntagResourceResponse {
}

export interface UpdateConfigRequest {
  readonly configData: ConfigTypeData;
  readonly configId: string;
  readonly configType: string;
  readonly name: string;
}

export interface UpdateMissionProfileRequest {
  readonly contactPostPassDurationSeconds?: number;
  readonly contactPrePassDurationSeconds?: number;
  readonly dataflowEdges?: [];
  readonly minimumViableContactDurationSeconds?: number;
  readonly missionProfileId: string;
  readonly name?: string;
  readonly trackingConfigArn?: string;
}

export interface UplinkEchoConfig {
  readonly antennaUplinkConfigArn: string;
  readonly enabled: boolean;
}

export interface UplinkSpectrumConfig {
  readonly centerFrequency: Frequency;
  readonly polarization?: string;
}


