/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface DescribeGroup {
  readonly IdentityStoreId: string;
  readonly GroupId: string;
}

export interface DescribeUser {
  readonly IdentityStoreId: string;
  readonly UserId: string;
}

export interface ListGroups {
  readonly IdentityStoreId: string;
  readonly MaxResults?: number;
  readonly NextToken?: string;
  readonly Filters?: [];
}

export interface ListUsers {
  readonly IdentityStoreId: string;
  readonly MaxResults?: number;
  readonly NextToken?: string;
  readonly Filters?: [];
}

export interface AccessDeniedException {
  readonly Message?: string;
  readonly RequestId?: string;
}

export interface DescribeGroupRequest {
  readonly IdentityStoreId: string;
  readonly GroupId: string;
}

export interface DescribeGroupResponse {
  readonly GroupId: string;
  readonly DisplayName: string;
}

export interface DescribeUserRequest {
  readonly IdentityStoreId: string;
  readonly UserId: string;
}

export interface DescribeUserResponse {
  readonly UserName: string;
  readonly UserId: string;
}

export interface Filter {
  readonly AttributePath: string;
  readonly AttributeValue: string;
}

export interface Group {
  readonly GroupId: string;
  readonly DisplayName: string;
}

export interface InternalServerException {
  readonly Message?: string;
  readonly RequestId?: string;
}

export interface ListGroupsRequest {
  readonly IdentityStoreId: string;
  readonly MaxResults?: number;
  readonly NextToken?: string;
  readonly Filters?: [];
}

export interface ListGroupsResponse {
  readonly Groups: [];
  readonly NextToken?: string;
}

export interface ListUsersRequest {
  readonly IdentityStoreId: string;
  readonly MaxResults?: number;
  readonly NextToken?: string;
  readonly Filters?: [];
}

export interface ListUsersResponse {
  readonly Users: [];
  readonly NextToken?: string;
}

export interface ResourceNotFoundException {
  readonly ResourceType?: string;
  readonly ResourceId?: string;
  readonly Message?: string;
  readonly RequestId?: string;
}

export interface ThrottlingException {
  readonly Message?: string;
  readonly RequestId?: string;
}

export interface User {
  readonly UserName: string;
  readonly UserId: string;
}

export interface ValidationException {
  readonly Message?: string;
  readonly RequestId?: string;
}


