/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface GetIceServerConfig {
  readonly ChannelARN: string;
  readonly ClientId?: string;
  readonly Service?: string;
  readonly Username?: string;
}

export interface SendAlexaOfferToMaster {
  readonly ChannelARN: string;
  readonly SenderClientId: string;
  readonly MessagePayload: string;
}

export interface ClientLimitExceededException {
  readonly Message?: string;
}

export interface GetIceServerConfigRequest {
  readonly ChannelARN: string;
  readonly ClientId?: string;
  readonly Service?: string;
  readonly Username?: string;
}

export interface GetIceServerConfigResponse {
  readonly IceServerList?: [];
}

export interface IceServer {
  readonly Uris?: [];
  readonly Username?: string;
  readonly Password?: string;
  readonly Ttl?: number;
}

export interface InvalidArgumentException {
  readonly Message?: string;
}

export interface InvalidClientException {
  readonly message?: string;
}

export interface NotAuthorizedException {
  readonly Message?: string;
}

export interface ResourceNotFoundException {
  readonly Message?: string;
}

export interface SendAlexaOfferToMasterRequest {
  readonly ChannelARN: string;
  readonly SenderClientId: string;
  readonly MessagePayload: string;
}

export interface SendAlexaOfferToMasterResponse {
  readonly Answer?: string;
}

export interface SessionExpiredException {
  readonly message?: string;
}


