/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface CreateHomeRegionControl {
  readonly HomeRegion: string;
  readonly Target: Target;
  readonly DryRun?: boolean;
}

export interface DescribeHomeRegionControls {
  readonly ControlId?: string;
  readonly HomeRegion?: string;
  readonly Target?: Target;
  readonly MaxResults?: number;
  readonly NextToken?: string;
}

export interface GetHomeRegion {
}

export interface AccessDeniedException {
  readonly Message?: string;
}

export interface CreateHomeRegionControlRequest {
  readonly HomeRegion: string;
  readonly Target: Target;
  readonly DryRun?: boolean;
}

export interface CreateHomeRegionControlResult {
  readonly HomeRegionControl?: HomeRegionControl;
}

export interface DescribeHomeRegionControlsRequest {
  readonly ControlId?: string;
  readonly HomeRegion?: string;
  readonly Target?: Target;
  readonly MaxResults?: number;
  readonly NextToken?: string;
}

export interface DescribeHomeRegionControlsResult {
  readonly HomeRegionControls?: [];
  readonly NextToken?: string;
}

export interface DryRunOperation {
  readonly Message?: string;
}

export interface GetHomeRegionRequest {
}

export interface GetHomeRegionResult {
  readonly HomeRegion?: string;
}

export interface HomeRegionControl {
  readonly ControlId?: string;
  readonly HomeRegion?: string;
  readonly Target?: Target;
  readonly RequestedTime?: Date;
}

export interface InternalServerError {
  readonly Message?: string;
}

export interface InvalidInputException {
  readonly Message?: string;
}

export interface ServiceUnavailableException {
  readonly Message?: string;
}

export interface Target {
  readonly Type: string;
  readonly Id?: string;
}

export interface ThrottlingException {
  readonly Message: string;
  readonly RetryAfterSeconds?: number;
}


