/**
 * STOP. This file is autogenerated. DO NOT EDIT by hand
 */
export interface CreateHomeRegionControl {
  readonly HomeRegion: string;
  readonly Target: Target;
  readonly DryRun?: boolean;
}
export interface DescribeHomeRegionControls {
  readonly ControlId?: string;
  readonly HomeRegion?: string;
  readonly Target?: Target;
  readonly MaxResults?: number;
  readonly NextToken?: string;
}
export interface GetHomeRegion {
}



interface AccessDeniedException {
  readonly Message: string;
}

interface CreateHomeRegionControlRequest {
  readonly HomeRegion: string;
  readonly Target: Target;
  readonly DryRun: boolean;
}

interface CreateHomeRegionControlResult {
  readonly HomeRegionControl: HomeRegionControl;
}

interface DescribeHomeRegionControlsRequest {
  readonly ControlId: string;
  readonly HomeRegion: string;
  readonly Target: Target;
  readonly MaxResults: number;
  readonly NextToken: string;
}

interface DescribeHomeRegionControlsResult {
  readonly HomeRegionControls: [];
  readonly NextToken: string;
}

interface DryRunOperation {
  readonly Message: string;
}

interface GetHomeRegionRequest {
}

interface GetHomeRegionResult {
  readonly HomeRegion: string;
}

interface HomeRegionControl {
  readonly ControlId: string;
  readonly HomeRegion: string;
  readonly Target: Target;
  readonly RequestedTime: Date;
}

interface InternalServerError {
  readonly Message: string;
}

interface InvalidInputException {
  readonly Message: string;
}

interface ServiceUnavailableException {
  readonly Message: string;
}

interface Target {
  readonly Type: string;
  readonly Id: string;
}

interface ThrottlingException {
  readonly Message: string;
  readonly RetryAfterSeconds: number;
}

